name: redenovo
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.5=py310hea249c9_0
  - decorator=5.1.1=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.30.0=pyh707e725_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgomp=14.1.0=h77fa898_0
  - liblapack=3.9.0=25_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=1.26.4=py310hb13e2d6_0
  - openssl=3.3.1=hb9d3cd8_3
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.48=pyha770c72_1
  - psutil=6.0.0=py310hc51659f_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.18.0=pyhd8ed1ab_1
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=5_cp310
  - pyzmq=26.2.0=py310h71f11fc_0
  - readline=8.2=h8228510_1
  - scikit-learn=1.5.1=py310h146d792_0
  - scipy=1.14.1=py310ha3fb0e1_0
  - setuptools=70.2.0=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py310hc51659f_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h75354e8_4
  - zipp=3.21.0=pyhd8ed1ab_1
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - configargparse==1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - gast==0.6.0
      - google-auth==2.32.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.65.0
      - h5py==3.11.0
      - idna==3.7
      - keras==2.15.0
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - optree==0.12.1
      - packaging==24.1
      - pandas==2.2.2
      - pillow==10.4.0
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyparsing==3.1.2
      - pytz==2024.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - six==1.16.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.3
      - wrapt==1.14.1
